### ISSUE TITLE
获取不到 notify 中数据.

### ISSUE THREAD

**Issue by oldfeel** [ascoders/alipay#10]
notify 中的 contro.Ctx.Input.CopyBody(beego.BConfig.MaxMemory) 是空值

bee   :1.4.1
beego :1.6.1
Go    :go version go1.6 linux/amd64

**Comment by ascoders** [comment]
beego后续可能有不兼容的改动，可以换成beego 1.4X版本，或者使用不依赖beego的方案，详情见readme：

```go
func ReturnHandle(w http.ResponseWriter, r *http.Request) {
    result := alipay.NativeReturn(r)
    if result.Status == 1 { //付款成功，处理订单
        //处理订单
    }
}
```
