### ISSUE TITLE
为什么要导入beego

### ISSUE THREAD

**Issue by weisd** [ascoders/alipay#12]
一个小库，导入一个大框架...  - -

**Comment by funnywwh** [comment]
这个是使用习惯吧，beego这个框架还是挺容易上手的

**Comment by weisd** [comment]
不用beego的人不是加载了一堆文件？
beego包又import了很多其他的包呢

**Comment by ascoders** [comment]
因为当初这个库是为beego定制的，现在也支持原生的写法，缺憾是引入了一些beego依赖库的init方法，但影响很小
