### ISSUE TITLE
aliplay 的form要怎么parse给前端 template

### ISSUE THREAD

**Issue by airbob** [ascoders/alipay#2]
你好,
不知道你的email,只好开了个issue请教一下这个问题
```
form := alipay.CreateAlipaySign("123", 19.8, "翱翔大空", "充值19.8元")
```
要怎么parse给前端正常显示。

我现在的做法是
```
form := alipay.CreateAlipaySign("123", 19.8, "翱翔大空", "充值19.8元")
this.Data["AlipayForm"] = form 
```

然后前端页面tpl里:
直接用{{.AlipayForm}}

但是出来的结果(查看html源代码)都是加了escape的
```
 &lt;form id=&#34;alipaysubmit&#34; name=&#34;
```
没有render 成html, 请问下正确的做法应该是怎么样的?

感谢!

**Comment by ascoders** [comment]
这是beego前端渲染的保护机制，其实生成的代码是正确的，只不过被安全转义了

想让模版显示出html代码的方法是

````
{{.AlipayForm | str2html}}
````

参考：http://beego.me/docs/mvc/view/template.md

**Comment by airbob** [comment]
惭愧,看beego文档没注意到这一块,谢谢!
