### ISSUE TITLE
go get 错误

### ISSUE THREAD

**Issue by 756445638** [ascoders/alipay#7]
[yuyang@localhost saintour]$ go get github.com/ascoders/alipay
# github.com/ascoders/alipay
../../ascoders/alipay/alipay.go:165: not enough arguments in call to contro.Ctx.Input.CopyBody
../../ascoders/alipay/alipay.go:175: not enough arguments in call to contro.Ctx.Input.CopyBody
../../ascoders/alipay/alipay.go:245: this.AlipayKey undefined (type *Client has no field or method AlipayKey)
../../ascoders/alipay/alipay_v1.go:135: not enough arguments in call to contro.Ctx.Input.CopyBody
../../ascoders/alipay/alipay_v1.go:145: not enough arguments in call to contro.Ctx.Input.CopyBody

**Comment by ascoders** [comment]
fixed #8
