### ISSUE TITLE
是不是与最新版的 beego 不兼容?

### ISSUE THREAD

**Issue by oldfeel** [ascoders/alipay#8]
使用 beego 1.6 报错

`not enough arguments in call to contro.Ctx.Input.CopyBody`

**Comment by oldfeel** [comment]
使用 bee fix 可修复
http://beego.me/docs/intro/upgrade.md

**Comment by 756445638** [comment]
我也是相同的问题，明明参数够了

**Comment by 756445638** [comment]
看错了吧contro.Ctx.Input.CopyBody，是这个方法没有传参数

**Comment by ascoders** [comment]
是的，最新版CopyBody需要一个传参，现在已经修复（PS：吐槽一下beego作者居然没有给此改动做兼容，而且修改后无法兼容1.5，支持大家都用最新版）
